spring:
  cloud:
    gateway:
      x-forwarded:
        prefixEnabled: false
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      # 路由到本机的9000端口上
      - id: file
        uri: lb://oa-file-server
        predicates:
        - Path=/file/**
        filters:
        - StripPrefix=1
        # 集成eureka注册中心的配置示例
      - id: authority
        uri: lb://oa-authority-server
        predicates:
        - Path=/api/authority/**
        filters:
        - StripPrefix=2
authentication:
  user:
    header-name: Authorization
    pub-key: client/pub.key    # 解密


gate:
  ignore:
    url: /**/swagger-ui.html,/**/doc.html,/**/webjars/**,/**/v2/api-docs/**,/**/v2/api-docs-ext/**,/**/swagger-resources/**,/**/auth/**
